import { Router } from 'express'; import { StatusCodes } from 'http-status-codes';
import BloqueoUsuarioService from '../services/BloqueoUsuarioService.js'; import BloqueoUsuario from '../entities/BloqueoUsuario.js';
const router = Router(); const currentService = new BloqueoUsuarioService();
router.get('', async (req, res) => { try { console.log('BloqueoUsuarioController.getAll'); const r = await currentService.getAllAsync(); if (r != null) { res.status(StatusCodes.OK).json(r); } else { res.status(StatusCodes.INTERNAL_SERVER_ERROR).send('Error interno.'); } } catch (error) { console.log(error); res.status(StatusCodes.INTERNAL_SERVER_ERROR).send(`Error: ${error.message}`); } });
router.get('/:id', async (req, res) => { try { const id = parseInt(req.params.id); console.log(`BloqueoUsuarioController.getById(${id})`); const r = await currentService.getByIdAsync(id); if (r != null) { res.status(StatusCodes.OK).json(r); } else { res.status(StatusCodes.NOT_FOUND).send(`No se encontro el bloqueo con id: ${id}.`); } } catch (error) { console.log(error); res.status(StatusCodes.INTERNAL_SERVER_ERROR).send(`Error: ${error.message}`); } });
router.post('', async (req, res) => { try { console.log('BloqueoUsuarioController.create'); const entity = new BloqueoUsuario(req.body); const newId = await currentService.createAsync(entity); if (newId > 0) { res.status(StatusCodes.CREATED).json({ message: `Se creo el bloqueo con id: ${newId}`, id: newId }); } else { res.status(StatusCodes.BAD_REQUEST).json({ message: 'No se pudo crear el bloqueo.' }); } } catch (error) { console.log(error); res.status(StatusCodes.BAD_REQUEST).send(`Error: ${error.message}`); } });
router.put('/:id', async (req, res) => { try { const id = parseInt(req.params.id); const entity = new BloqueoUsuario(req.body); console.log(`BloqueoUsuarioController.update(${id})`); if (entity.id && parseInt(entity.id) !== id) { return res.status(StatusCodes.BAD_REQUEST).send(`El id de la URL (${id}) no coincide con el id del body (${entity.id}).`); } entity.id = id; const rowsAffected = await currentService.updateAsync(entity); if (rowsAffected !== 0) { res.status(StatusCodes.OK).json({ message: `Se actualizo el bloqueo con id: ${id}`, rowsAffected }); } else { res.status(StatusCodes.NOT_FOUND).send(`No se encontro el bloqueo con id: ${id}.`); } } catch (error) { console.log(error); res.status(StatusCodes.BAD_REQUEST).send(`Error: ${error.message}`); } });
router.delete('/:id', async (req, res) => { try { const id = parseInt(req.params.id); console.log(`BloqueoUsuarioController.delete(${id})`); const rowCount = await currentService.deleteByIdAsync(id); if (rowCount !== 0) { res.status(StatusCodes.OK).json({ message: `Se desactivo el bloqueo con id: ${id}`, rowsAffected: rowCount }); } else { res.status(StatusCodes.NOT_FOUND).send(`No se encontro el bloqueo con id: ${id}.`); } } catch (error) { console.log(error); res.status(StatusCodes.INTERNAL_SERVER_ERROR).send(`Error: ${error.message}`); } });
export default router;
