import { Router } from 'express';
import EventoService from '../services/EventoService.js';
const router = Router();
router.get('/eventos', async (req, res, next) => { try { res.status(200).json({ ok: true, data: await EventoService.list() }); } catch (e) { next(e); } });
router.get('/eventos/:id', async (req, res, next) => { try { res.status(200).json({ ok: true, data: await EventoService.getById(Number(req.params.id)) }); } catch (e) { next(e); } });
router.post('/eventos', async (req, res, next) => { try { res.status(201).json({ ok: true, data: await EventoService.create(req.body) }); } catch (e) { next(e); } });
router.put('/eventos/:id', async (req, res, next) => { try { res.status(200).json({ ok: true, data: await EventoService.update(Number(req.params.id), req.body) }); } catch (e) { next(e); } });
router.delete('/eventos/:id', async (req, res, next) => { try { await EventoService.remove(Number(req.params.id)); res.status(204).send(); } catch (e) { next(e); } });
router.get('/perteneciente/:idPerteneciente', async (req, res, next) => { try { res.status(200).json({ ok: true, data: await EventoService.listByPerteneciente(Number(req.params.idPerteneciente)) }); } catch (e) { next(e); } });
export default router;
