import { Router } from 'express'; import { StatusCodes } from 'http-status-codes';
import ConfiguracionUsuarioService from '../services/ConfiguracionUsuarioService.js'; import ConfiguracionUsuario from '../entities/ConfiguracionUsuario.js';
const router = Router(); const currentService = new ConfiguracionUsuarioService();
router.get('', async (req, res) => { try { console.log('ConfiguracionUsuarioController.getAll'); const r = await currentService.getAllAsync(); if (r != null) { res.status(StatusCodes.OK).json(r); } else { res.status(StatusCodes.INTERNAL_SERVER_ERROR).send('Error interno.'); } } catch (error) { console.log(error); res.status(StatusCodes.INTERNAL_SERVER_ERROR).send(`Error: ${error.message}`); } });
router.get('/:id', async (req, res) => { try { const id = parseInt(req.params.id); console.log(`ConfiguracionUsuarioController.getById(${id})`); const r = await currentService.getByIdAsync(id); if (r != null) { res.status(StatusCodes.OK).json(r); } else { res.status(StatusCodes.NOT_FOUND).send(`No se encontró la configuración con id: ${id}.`); } } catch (error) { console.log(error); res.status(StatusCodes.INTERNAL_SERVER_ERROR).send(`Error: ${error.message}`); } });
router.post('', async (req, res) => { try { console.log('ConfiguracionUsuarioController.create'); const entity = new ConfiguracionUsuario(req.body); const newId = await currentService.createAsync(entity); if (newId > 0) { res.status(StatusCodes.CREATED).json({ message: `Se creó la configuración con id: ${newId}`, id: newId }); } else { res.status(StatusCodes.BAD_REQUEST).json({ message: 'No se pudo crear la configuración.' }); } } catch (error) { console.log(error); res.status(StatusCodes.BAD_REQUEST).send(`Error: ${error.message}`); } });
router.put('/:id', async (req, res) => { try { const id = parseInt(req.params.id); const entity = new ConfiguracionUsuario(req.body); console.log(`ConfiguracionUsuarioController.update(${id})`); if (entity.id && parseInt(entity.id) !== id) { return res.status(StatusCodes.BAD_REQUEST).send(`El id de la URL (${id}) no coincide con el id del body (${entity.id}).`); } entity.id = id; const rowsAffected = await currentService.updateAsync(entity); if (rowsAffected !== 0) { res.status(StatusCodes.OK).json({ message: `Se actualizó la configuración con id: ${id}`, rowsAffected }); } else { res.status(StatusCodes.NOT_FOUND).send(`No se encontró la configuración con id: ${id}.`); } } catch (error) { console.log(error); res.status(StatusCodes.BAD_REQUEST).send(`Error: ${error.message}`); } });
router.delete('/:id', async (req, res) => { try { const id = parseInt(req.params.id); console.log(`ConfiguracionUsuarioController.delete(${id})`); const rowCount = await currentService.deleteByIdAsync(id); if (rowCount !== 0) { res.status(StatusCodes.OK).json({ message: `Se eliminó la configuración con id: ${id}`, rowsAffected: rowCount }); } else { res.status(StatusCodes.NOT_FOUND).send(`No se encontró la configuración con id: ${id}.`); } } catch (error) { console.log(error); res.status(StatusCodes.INTERNAL_SERVER_ERROR).send(`Error: ${error.message}`); } });
export default router;
