import { Router } from 'express';
import EmocionService from '../services/EmocionService.js';
const router = Router();
router.get('/', async (req, res, next) => { try { res.status(200).json({ ok: true, data: await EmocionService.list() }); } catch (e) { next(e); } });
router.get('/perteneciente/:idPerteneciente', async (req, res, next) => { try { res.status(200).json({ ok: true, data: await EmocionService.listByPerteneciente(Number(req.params.idPerteneciente)) }); } catch (e) { next(e); } });
router.get('/:id', async (req, res, next) => { try { res.status(200).json({ ok: true, data: await EmocionService.getById(Number(req.params.id)) }); } catch (e) { next(e); } });
router.post('/', async (req, res, next) => { try { res.status(201).json({ ok: true, data: await EmocionService.create(req.body) }); } catch (e) { next(e); } });
router.put('/:id', async (req, res, next) => { try { res.status(200).json({ ok: true, data: await EmocionService.update(Number(req.params.id), req.body) }); } catch (e) { next(e); } });
router.delete('/:id', async (req, res, next) => { try { await EmocionService.remove(Number(req.params.id)); res.status(204).send(); } catch (e) { next(e); } });
export default router;
