import { Router } from 'express';
import ObjetivoService from '../services/ObjetivoService.js';
const router = Router();
router.get('/', async (req, res, next) => { try { res.status(200).json({ ok: true, data: await ObjetivoService.list() }); } catch (e) { next(e); } });
router.get('/perteneciente/:idPerteneciente', async (req, res, next) => { try { res.status(200).json({ ok: true, data: await ObjetivoService.listByPerteneciente(Number(req.params.idPerteneciente)) }); } catch (e) { next(e); } });
router.get('/:id', async (req, res, next) => { try { res.status(200).json({ ok: true, data: await ObjetivoService.getById(Number(req.params.id)) }); } catch (e) { next(e); } });
router.post('/', async (req, res, next) => { try { res.status(201).json({ ok: true, data: await ObjetivoService.create(req.body) }); } catch (e) { next(e); } });
router.put('/:id', async (req, res, next) => { try { res.status(200).json({ ok: true, data: await ObjetivoService.update(Number(req.params.id), req.body) }); } catch (e) { next(e); } });
router.delete('/:id', async (req, res, next) => { try { await ObjetivoService.remove(Number(req.params.id)); res.status(204).send(); } catch (e) { next(e); } });
export default router;
