import { Router } from 'express'; import { StatusCodes } from 'http-status-codes';
import ReporteUsuarioService from '../services/ReporteUsuarioService.js'; import ReporteUsuario from '../entities/ReporteUsuario.js';
const router = Router(); const currentService = new ReporteUsuarioService();
router.get('', async (req, res) => { try { console.log('ReporteUsuarioController.getAll'); const r = await currentService.getAllAsync(); if (r != null) { res.status(StatusCodes.OK).json(r); } else { res.status(StatusCodes.INTERNAL_SERVER_ERROR).send('Error interno.'); } } catch (error) { console.log(error); res.status(StatusCodes.INTERNAL_SERVER_ERROR).send(`Error: ${error.message}`); } });
router.get('/:id', async (req, res) => { try { const id = parseInt(req.params.id); console.log(`ReporteUsuarioController.getById(${id})`); const r = await currentService.getByIdAsync(id); if (r != null) { res.status(StatusCodes.OK).json(r); } else { res.status(StatusCodes.NOT_FOUND).send(`No se encontró el reporte con id: ${id}.`); } } catch (error) { console.log(error); res.status(StatusCodes.INTERNAL_SERVER_ERROR).send(`Error: ${error.message}`); } });
router.post('', async (req, res) => { try { console.log('ReporteUsuarioController.create'); const entity = new ReporteUsuario(req.body); const newId = await currentService.createAsync(entity); if (newId > 0) { res.status(StatusCodes.CREATED).json({ message: `Se creó el reporte con id: ${newId}`, id: newId }); } else { res.status(StatusCodes.BAD_REQUEST).json({ message: 'No se pudo crear el reporte.' }); } } catch (error) { console.log(error); res.status(StatusCodes.BAD_REQUEST).send(`Error: ${error.message}`); } });
router.put('/:id', async (req, res) => { try { const id = parseInt(req.params.id); const entity = new ReporteUsuario(req.body); console.log(`ReporteUsuarioController.update(${id})`); if (entity.id && parseInt(entity.id) !== id) { return res.status(StatusCodes.BAD_REQUEST).send(`El id de la URL (${id}) no coincide con el id del body (${entity.id}).`); } entity.id = id; const rowsAffected = await currentService.updateAsync(entity); if (rowsAffected !== 0) { res.status(StatusCodes.OK).json({ message: `Se actualizó el reporte con id: ${id}`, rowsAffected }); } else { res.status(StatusCodes.NOT_FOUND).send(`No se encontró el reporte con id: ${id}.`); } } catch (error) { console.log(error); res.status(StatusCodes.BAD_REQUEST).send(`Error: ${error.message}`); } });
router.delete('/:id', async (req, res) => { try { const id = parseInt(req.params.id); console.log(`ReporteUsuarioController.delete(${id})`); const rowCount = await currentService.deleteByIdAsync(id); if (rowCount !== 0) { res.status(StatusCodes.OK).json({ message: `Se eliminó el reporte con id: ${id}`, rowsAffected: rowCount }); } else { res.status(StatusCodes.NOT_FOUND).send(`No se encontró el reporte con id: ${id}.`); } } catch (error) { console.log(error); res.status(StatusCodes.INTERNAL_SERVER_ERROR).send(`Error: ${error.message}`); } });
export default router;
